session_inspector.settings:
  type: config_object
  label: 'Session Inspector settings.'
  mapping:
    browser_format:
      type: string
      label: 'The browser format plugin.'
    hostname_format:
      type: string
      label: 'The hostname format plugin.'
    date_format:
      type: string
      label: 'The date format.'
    date_interval_include:
      type: boolean
      label: 'Include the time interval string.'
