<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function getjwtonlogin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.getjwtonlogin':
      return t('
        <h2>getjwtonlogin</h2>
        <h3>Instructions</h3>
        <p>This module requires no configuration... <strong>Just install the module to use it!</strong></p>
      ');
  }
}

/**
 * Implements hook_form_alter().
 */
function getjwtonlogin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'user_login_form' || $form_id == 'user_pass') {
	$form['#validate'][] = 'getjwtonlogin_validation_function';
	return $form;
  }
}

/**
 * Function to validate the host.
 */
function getjwtonlogin_validation_function($form, FormStateInterface $form_state) {
  
  // List of all Concierto portals.
  $hostList = array("dev-userapi.concierto.cloud", "uat-userapi.concierto.cloud", "demo-userapi.concierto.cloud", "apacpp-userapi.concierto.cloud","trz-userapi.concierto.cloud", "us-east-userapi.concierto.cloud", "dev-user.concierto.cloud", "uat-user.concierto.cloud", "demo-user.concierto.cloud", "apacpp-user.concierto.cloud", "trz-user.concierto.cloud", "us-east-user.concierto.cloud",  "dev.concierto.cloud", "uat.concierto.cloud", "demo.concierto.cloud", "apacpp.concierto.cloud", "trz.concierto.cloud", "us-east.concierto.cloud", "localhost");
  
  $current_request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!in_array($current_request->headers->get('host'), $hostList)) {
	$form_state->setErrorByName('Invalid Host', t('Unknown Host is trying to login'));  
  }
  
  return $form;
}
