<?php

function contentservice_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if ($form_id == 'user_form') {
	   unset($form['field_last_password_reset']);
	   unset($form['field_pending_expire_sent']);
	   unset($form['field_password_expiration']);
  }
}

class contentservice_data {
       function getip() {
        if (getenv('HTTP_X_FORWARDED_FOR')) {
            $ip = getenv('HTTP_X_FORWARDED_FOR');
        } elseif (getenv('HTTP_X_REAL_IP')) {
            $ip = getenv('HTTP_X_REAL_IP');
        } else {
            $ip = $_SERVER['REMOTE_ADDR'];
        }

        return $ip;
    }
}