<?php

/**
 * @file
 * Contains rest_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_log module.
    case 'help.page.rest_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('all rest log') . '</p>';
      return $output;

    default:
  }
}
