<?php

/**
 * @file
 * Domain role access module.
 */

use Drupal\Core\Url;
use Drupal\domain\DomainInterface;

/**
 * Implements hook_domain_operations().
 */
function domain_role_access_domain_operations(DomainInterface $domain) {
  $id = $domain->id();
  $operations['domain_role_access'] = [
    'title' => t('Roles'),
    'url' => Url::fromRoute('domain_role_access.admin', ['domain' => $id]),
    'weight' => 80,
  ];
  return $operations;
}
