negate: '0'
roles:
  anonymous: anonymous
  authenticated: 0
  ibm_admin: 0
  whirlpool_admin: 0
  whirlpool_review: 0
  whirlpool_editor: 0
_core:
  default_config_hash: hO8iwMW7BHFHqHZCQTEy2zm_9JILgQy4Bz2ghGnw2xw
