_core:
  default_config_hash: PJP3-sJN2SQZTgCupMBEHry3ui7zsl93xtTovoTanFU
remember_domain: false
path_pages: "/admin/appearance\r\n/admin/config/system/site-information\r\n/admin/config/domain/domain_access\r\n/admin/config/services/jsonapi/role_access\r\n/admin/config/services/rest/resource/plus_get_user_info/edit\r\n/admin/config/services/key-auth\r\n/admin/config/system/jwt\r\n/admin/config/system/phpmailer-smtp\r\n/admin/config/system/smtp"
