_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
name: 'User Portral'
mail: onboard@concierto.cloud
simple_address: false
sitestyle: false
textonly: false
linkonly: false
format: full_html
preserve_class: false
advanced:
  incoming: false
  key: h-_dw5IO7h0eZqLUzTg3gBCSJD7UscUXOLWi3hhdano
