_core:
  default_config_hash: Wkmn-jEru9OubwF4XTXJNzX89A62mX8PlyDco6TMYl4
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: 25
smtp_protocol: tls
smtp_username: onboard@concierto.cloud
smtp_password: sjswrlrdxwvvtlcs
smtp_hide_password: false
smtp_authentication_type: basic_auth
smtp_fromname: 'User Portral'
smtp_always_replyto: true
smtp_keepalive: false
smtp_debug: 0
smtp_debug_log: false
phpmailer_smtp_test: ''
smtp_ssl_verify_peer: true
smtp_ssl_verify_peer_name: true
smtp_ssl_allow_self_signed: false
smtp_envelope_sender_option: default
smtp_envelope_sender: ''
smtp_ehlo_host: ''
smtp_timeout: 300
