_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
smtp_on: false
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 300
smtp_username: userportal@concierto.cloud
smtp_password: tyrvbytsnxvdqmsq
smtp_from: userportal@concierto.cloud
smtp_fromname: 'User Portal'
smtp_client_hostname: 'Testing user portal uat email'
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: true
